function json(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json;charset=UTF-8'}})}
function cors(res){const h=new Headers(res.headers);h.set('access-control-allow-origin','*');h.set('access-control-allow-methods','GET,POST,PUT,DELETE,OPTIONS');h.set('access-control-allow-headers','Content-Type');return new Response(res.body,{status:res.status,headers:h})}
async function products(db){return (await db.prepare('SELECT id,barcode,sku,product_name,category,unit,beginning_stock,reorder_level,unit_cost,created_at,updated_at FROM products ORDER BY product_name').all()).results||[]}
export default{async fetch(request,env){const url=new URL(request.url);if(request.method==='OPTIONS')return new Response(null,{status:204,headers:{'access-control-allow-origin':'*','access-control-allow-methods':'GET,POST,PUT,DELETE,OPTIONS','access-control-allow-headers':'Content-Type'}});if(url.pathname.startsWith('/api/')){try{if(!env.DB)return cors(json({error:'D1 binding DB is missing.'},500));const db=env.DB,path=url.pathname.replace(/^\/api\/?/,'').replace(/\/+$/,'');
if(request.method==='GET'&&path==='products')return cors(json({products:await products(db)}));
if(request.method==='GET'&&path==='movements'){const r=await db.prepare(`SELECT sm.id,sm.product_id,sm.movement_type,sm.quantity,sm.reference,sm.notes,sm.created_at,p.barcode,p.product_name FROM stock_movements sm JOIN products p ON p.id=sm.product_id ORDER BY sm.created_at DESC`).all();return cors(json({movements:r.results||[]}))}
if(request.method==='POST'&&path==='products'){const b=await request.json();if(!b.barcode||!b.product_name)return cors(json({error:'Barcode and product name are required.'},400));const now=new Date().toISOString();const r=await db.prepare(`INSERT INTO products (barcode,sku,product_name,category,unit,beginning_stock,reorder_level,unit_cost,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?)`).bind(String(b.barcode).trim(),String(b.sku||'').trim(),String(b.product_name).trim(),String(b.category||'').trim(),String(b.unit||'pcs').trim(),Number(b.beginning_stock||0),Number(b.reorder_level||0),Number(b.unit_cost||0),now,now).run();return cors(json({ok:true,id:r.meta?.last_row_id??null},201))}
const pm=path.match(/^products\/(\d+)$/);if(pm&&request.method==='PUT'){const id=Number(pm[1]),b=await request.json();await db.prepare(`UPDATE products SET barcode=?,sku=?,product_name=?,category=?,unit=?,beginning_stock=?,reorder_level=?,unit_cost=?,updated_at=? WHERE id=?`).bind(String(b.barcode).trim(),String(b.sku||'').trim(),String(b.product_name).trim(),String(b.category||'').trim(),String(b.unit||'pcs').trim(),Number(b.beginning_stock||0),Number(b.reorder_level||0),Number(b.unit_cost||0),new Date().toISOString(),id).run();return cors(json({ok:true}))}
if(request.method==='POST'&&path==='movements'){const b=await request.json();if(!b.barcode||!['IN','OUT'].includes(b.movement_type)||Number(b.quantity)<=0)return cors(json({error:'Barcode, IN/OUT type and positive quantity are required.'},400));const p=await db.prepare('SELECT id,product_name FROM products WHERE barcode=?').bind(String(b.barcode).trim()).first();if(!p)return cors(json({error:'Barcode not found.'},404));const qty=Number(b.quantity);if(b.movement_type==='OUT'){const r=await db.prepare(`SELECT COALESCE((SELECT beginning_stock FROM products WHERE id=?),0)+COALESCE(SUM(CASE WHEN movement_type='IN' THEN quantity WHEN movement_type='OUT' THEN -quantity ELSE 0 END),0) AS current FROM stock_movements WHERE product_id=?`).bind(p.id,p.id).first();if(qty>Number(r?.current||0))return cors(json({error:`Not enough stock. Current stock: ${Number(r?.current||0)}`},400))}const r=await db.prepare(`INSERT INTO stock_movements (product_id,movement_type,quantity,reference,notes,created_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(p.id,b.movement_type,qty,String(b.reference||''),String(b.notes||'')).run();return cors(json({ok:true,id:r.meta?.last_row_id??null},201))}
return cors(json({error:'Not found'},404))}catch(e){return cors(json({error:e?.message||String(e)},500))}}
return env.ASSETS.fetch(request)}};
